### ISSUE TITLE
Shieldon (MT 63) should have +20 weakness, not +40

### ISSUE THREAD

**Issue by starg09** [tcgone/carddb#74]
https://github.com/tcgone/carddb/blob/a3073ef07c037dc49bcdc6be4c950770b0af0126/src/main/resources/cards/252-mysterious_treasures.yaml#L619

**Comment by scoot404** [comment]
The marked line in the issue is for Bastiodon (MT 21), who has the correct weakness of +40. Shieldon (MT 63) does have +20 weakness. (line 1813)

Unsure if this was left open after fixed or if there was a misreading. Regardless, issue is technically fixed

https://github.com/tcgone/carddb/blob/a3073ef07c037dc49bcdc6be4c950770b0af0126/src/main/resources/cards/252-mysterious_treasures.yaml#L1813
